/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSquadRouteImport } from './routes/_authenticated/squad'
import { Route as AuthenticatedTableRouteImport } from './routes/_authenticated/table'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as AuthenticatedMatchesMatchIdRouteImport } from './routes/_authenticated/matches.$matchId'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players.$playerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadRoute = AuthenticatedSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableRoute = AuthenticatedTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesMatchIdRoute =
  AuthenticatedMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/news': typeof AuthenticatedNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/squad': typeof AuthenticatedSquadRoute
  '/table': typeof AuthenticatedTableRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/news': typeof AuthenticatedNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/squad': typeof AuthenticatedSquadRoute
  '/table': typeof AuthenticatedTableRoute
  '/': typeof AuthenticatedIndexRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/squad': typeof AuthenticatedSquadRoute
  '/_authenticated/table': typeof AuthenticatedTableRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/news'
    | '/settings'
    | '/squad'
    | '/table'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/history'
    | '/news'
    | '/settings'
    | '/squad'
    | '/table'
    | '/'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/matches'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/news'
    | '/_authenticated/settings'
    | '/_authenticated/squad'
    | '/_authenticated/table'
    | '/_authenticated/'
    | '/_authenticated/matches/$matchId'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad': {
      id: '/_authenticated/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof AuthenticatedSquadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/table': {
      id: '/_authenticated/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AuthenticatedTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$matchId': {
      id: '/_authenticated/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSquadRoute: typeof AuthenticatedSquadRoute
  AuthenticatedTableRoute: typeof AuthenticatedTableRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchesMatchIdRoute: typeof AuthenticatedMatchesMatchIdRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSquadRoute: AuthenticatedSquadRoute,
  AuthenticatedTableRoute: AuthenticatedTableRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchesMatchIdRoute: AuthenticatedMatchesMatchIdRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
